services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - maxbrain
    depends_on:
      - backend
  backend:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - maxbrain
    env_file: 
      - ./server/.env

networks:
  maxbrain:
    driver: bridge